import 'antd/es/style/index'
import 'antd/es/button/style/index'
// import 'antd/es/badge/style/index'
import 'antd/es/switch/style/index'
// import 'antd/es/message/style/index'
// import 'antd/es/space/style/index'
// import 'antd/es/form/style/index'
import 'antd/es/tooltip/style/index'
// import 'antd/es/table/style/index'
// import 'antd/es/tag/style/index'
import 'antd/es/pagination/style/index'
// import 'antd/es/alert/style/index'
// import 'antd/es/card/style/index'
import 'antd/es/popconfirm/style/index'
import 'antd/es/popover/style/index'
// import 'antd/es/time-picker/style/index'
// import 'antd/es/date-picker/style/index'
// import 'antd/es/input-number/style/index'
// import 'antd/es/input/style/index'
// import 'antd/es/select/style/index'
import 'antd/es/modal/style/index'
import 'antd/es/drawer/style/index'
import 'antd/es/result/style/index'
// import 'antd/es/empty/style/index'
import 'antd/es/grid/style/index'
import 'antd/es/dropdown/style/index'
import 'antd/es/menu/style/index'
// import 'antd/es/textarea/style/index'
// import 'antd/es/checkbox/style/index'
// import 'antd/es/rate/style/index'
// import 'antd/es/radio/style/index'
// import 'antd/es/cascader/style/index'
