import ProTable from './ProTable'
// import './style.less'
export { default as useEditFieldPlugin } from './plugins/editField'
export { default as useQueryFieldPlugin } from './plugins/queryField'
export { default as useTablePlugin } from './plugins/table'
export { default as useValueTypePlugin } from './plugins/valueType'
export { default as useActionsPlugin } from './plugins/actions'
export { default as useConfigPlugin } from './plugins/config'
export { default as useModalPlugin } from './plugins/modal'
export { createPlugin, setDefaultProps } from './utils'
export { builtInPlugins, createProTable, useProTableRef, ProTable } from './ProTable'
export * from './types'
// export { default as Button } from './components/Button'
// export { default as Popconfirm } from './components/Popconfirm'
// export { default as Switch } from './components/Switch'
// export { default as FormItem } from './components/FormItem'
export default ProTable
